package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.27

import (
	"context"
	"os"

	"github.com/zenith110/Portfolio-Backend/graph/generated"
	"github.com/zenith110/Portfolio-Backend/graph/model"
	"github.com/zenith110/Portfolio-Backend/graph/routes"
)

// GithubProjects is the resolver for the githubProjects field.
func (r *queryResolver) GithubProjects(ctx context.Context) (*model.GithubProjects, error) {
	githubUser := os.Getenv("GITHUBUSER")
	github, err := routes.FetchProjects(githubUser)
	return github, err
}

// NotionGoals is the resolver for the notionGoals field.
func (r *queryResolver) NotionGoals(ctx context.Context) (*model.NotionGoals, error) {
	intergrationToken := os.Getenv("INTERGRATIONTOKEN")
	notionGoals, err := routes.FetchNotionPage(intergrationToken)
	return notionGoals, err
}

// Profile is the resolver for the profile field.
func (r *queryResolver) Profile(ctx context.Context) (*model.GithubBio, error) {
	githubUser := os.Getenv("GITHUBUSER")
	githubBio, err := routes.GrabProfileData(githubUser)
	return githubBio, err
}

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, input *model.SearchInput) (*model.Articles, error) {
	articles, err := routes.ZincSearch(input)
	return articles, err
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
