// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GithubBio struct {
	Position string `json:"position"`
	Company  string `json:"company"`
	Readme   string `json:"readme"`
}

type GithubProjects struct {
	Projects         []*Project `json:"projects"`
	ContributorCount int        `json:"contributorCount"`
}

type NotionGoals struct {
	Goals []string `json:"goals"`
}

type Project struct {
	Name           string   `json:"name"`
	Githublink     string   `json:"githublink"`
	Description    string   `json:"description"`
	Createdon      string   `json:"createdon"`
	Languages      []Tag    `json:"languages"`
	Topics         []string `json:"topics"`
	Deploymentlink string   `json:"deploymentlink"`
}

type Tag struct {
	Language string `json:"language"`
}
